### ISSUE TITLE
the trend values with 95% ci

### ISSUE THREAD

**Issue by Yalthoba1407** [chaolongwang/SAPHIRE#2]
Hi ,
I ran your SAPHIRE code and tried to match the fit results with what you have written in your paper. The code results did not show the predicted trend values with 95% CI. Can you please tell me how did you do that and I will be grateful to you?

**Comment by dwuab** [comment]
@Yalthoba1407 Could you describe in more details on (1) how you ran the code and (2) what you got?

**Comment by Yalthoba1407** [comment]
thanks for your reply.
I ran the script main and I got the result for figure two which represent the following:
Parameters were estimated by fitting data from 1 January to 29 February. a, Prediction using parameters from period 5 (17 February–29 February). b, Distribution of Re estimates from 10,000 MCMC samples. c, Prediction using parameters from period 4 (2 February–16 February). d, Prediction using parameters from period 3 (23 January to 1 February). e, Prediction using parameters from period 2 (10 January to 22 January). The shaded areas in a, c–e are 95% credible intervals, and the coloured points are the mean values based on 10,000 MCMC samples. f, Estimated number of active infectious cases in Wuhan from 1 January to 8 March.

summary_run_main_analysis provided the estimated parameters values ,Re and when (I =0 and P+A+I= 0 )
UNTIL NOW EVERYTHING IS CLEAR

then you mentioned that
you  estimated the cumulative number of infections, including unascertained cases, up until 8 March to be 258,728 (204,783–320,145) if the trend of the fourth period was assumed (Fig. 2c), 818,724 (599,111–1,096,850) if the trend of the third period was assumed (Fig. 2d) or 6,302,694 (6,275,508–6,327,520) if the trend of the second period was assumed (Fig. 2e), in comparison to the estimated total infections of 249,187 (198,412–307,062) obtained by fitting data from all 5 periods (Fig. 2a)

I want to know more about how did you get the cumulative number of infection up until 8 March to be 258,728 (204,783–320,145),if the trend of the fourth period was assumed (Fig. 2c), 818,724 (599,111–1,096,850).....


thanks in advance

**Comment by dwuab** [comment]
You could do it like this (the following code assumes the output of the main script `pars_est_run_main_analysis.txt` is placed at the right place):
```
code_root="/path/to/SAPHIRE/"
setwd(paste0(code_root, "output"))
source(paste0(code_root, "R/fun_SEIRsimu.R"))
source(paste0(code_root, "R/init_cond.R"))


#############################       Predicted_infections_on_Mar8   
####################################
init_sets_list <- get_init_sets_list(r0 = 0.23)
init_sets_list$days_to_fit <- 1:68
pars_ests <- as.matrix(read.table("pars_est_run_main_analysis.txt", header = T))
pars_ests <- tail(pars_ests, 10000)
## Mar 8 / five periods
est_infect_mat <- NULL
estS <- apply(pars_ests, 1, function(x) SEIRsimu(pars = x, init_settings = init_sets_list, num_periods = 5)[68, "S"])
est_infect <- init_sets_list$N - estS
est_infect_mat <- cbind(est_infect_mat, est_infect)
#
estS <- apply(pars_ests, 1, function(x) SEIRsimu(pars = x, init_settings = init_sets_list, num_periods = 4)[68, "S"])
est_infect <- init_sets_list$N - estS
est_infect_mat <- cbind(est_infect_mat, est_infect)
...
stat_mean <- apply(est_infect_mat, 2, function(x) round(mean(x), 0))
stat_quant <- apply(est_infect_mat, 2, function(x) round(quantile(x, c(0.025, 0.975)), 0))
stat_mean
stat_quant
```
By adjusting `num_periods` argument in the `SEIRsimu` call, you will get predictions assuming the trend of the 2nd, 3rd, or the 4th period. With different random seeds, the numbers could be different, but should not be very similar to those reported in the paper. Let me know if you still have problems.

**Comment by Yalthoba1407** [comment]
Thank you so much for answering my questions. One thing I realized in summary_run_main_analysis that delta comes as negative. I wonder why it is negative in your code results and positive in your article. Thank you so much for your cooperation

**Comment by dwuab** [comment]
I'm glad my answers are helpful to you. 
Regarding "delta", I assume you meant delta3, delta4 and delta5. We parameterize r3, r4 and r5 so that deltas could be negative or positive, but r3, r4 and r5 are always positive. See the three unnumbered equations immediately after equation 9. And in our calculations, some of the deltas did turn out negative.
In our paper, we presented r3, r4 and r5 directly without mentioning delta3, delta4 and delta5 r3, r4 and r5 presented in our paper were always positive by definition.

If you don't have further question, I will close this issue. You could open an new issue if you have questions concerning other aspects of our work.

**Comment by Yalthoba1407** [comment]
Thanks a lot for all your help.

**Comment by Yalthoba1407** [comment]
Hi,
Thank you so much for all your response. I have the following questions:
1- what kind of stochastic simulation did you use for prediction and risk or resurgence? 
2- in the code, how did you calculate the probability of resurgence?
I really appreciate your time and help and if you can provide your email instead of creating an issue in your GitHub, that will help a lot. 

thanks in advance,

**Comment by dwuab** [comment]
Hi Yalthoba1407,
1) I think we have described our simulation adequately in the Methods section of the paper.
2) "We calculated the probability of resurgence as the proportion of simulations in which resurgence occurred, as well as the time to resurgence conditional on the occur- rence of resurgence."

**Comment by Yalthoba1407** [comment]
Hi Degang Wu, 
Thank you so much for your answers. I read the paper, and I got some ideas about what kind of stochastic simulation it is, but not that sure. As you know, stochastic simulation is a huge topic, and if you can highlight some details, I thank that would help a lot as I am not expert on this topic.
